---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cost-monitor-network-policy
  labels:
    app: cost-monitor
spec:
  podSelector:
    matchLabels:
      app: cost-monitor
  policyTypes:
  - Ingress
  - Egress

  # Ingress rules
  ingress:
  # Allow traffic from OpenShift router
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-ingress
    ports:
    - protocol: TCP
      port: 8050  # Dashboard
    - protocol: TCP
      port: 8051  # API
    - protocol: TCP
      port: 8080  # Health checks

  # Allow internal communication between dashboard and API
  - from:
    - podSelector:
        matchLabels:
          app: cost-monitor
    ports:
    - protocol: TCP
      port: 8050
    - protocol: TCP
      port: 8051
    - protocol: TCP
      port: 8080

  # Allow monitoring from OpenShift monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-monitoring
    ports:
    - protocol: TCP
      port: 9090  # Metrics

  # Egress rules
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

  # Allow HTTPS to cloud provider APIs
  - to: []
    ports:
    - protocol: TCP
      port: 443

  # Allow HTTP for health checks and internal communication
  - to:
    - podSelector:
        matchLabels:
          app: cost-monitor
    ports:
    - protocol: TCP
      port: 8050
    - protocol: TCP
      port: 8051
    - protocol: TCP
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cost-monitor-deny-all
  labels:
    app: cost-monitor
spec:
  podSelector:
    matchLabels:
      app: cost-monitor
  policyTypes:
  - Ingress
  - Egress
  # Empty rules = deny all by default (this policy provides baseline security)