apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-data-service
  labels:
    app: cost-monitor
    component: data-service
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: cost-data-service
      component: data-service
  template:
    metadata:
      labels:
        app: cost-data-service
        component: data-service
        tier: backend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cost-data-service
        image: image-registry.openshift-image-registry.svc:5000/cost-monitor/cost-data-service:latest
        imagePullPolicy: Always

        ports:
        - name: api
          containerPort: 8000
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP

        env:
        - name: ENVIRONMENT
          value: "production"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        - name: POSTGRESQL_DATABASE
          value: "cost_monitor"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: REDIS_HOST
          value: "redis-service"

        # Cloud Provider Credentials (dynaconf configuration format only)

        # AWS Configuration
        - name: CLOUDCOST__CLOUDS__AWS__ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: CLOUDCOST__CLOUDS__AWS__SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: CLOUDCOST__CLOUDS__AWS__REGION
          value: "us-east-1"

        # Azure Configuration
        - name: CLOUDCOST__CLOUDS__AZURE__CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client-id
        - name: CLOUDCOST__CLOUDS__AZURE__CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client-secret
        - name: CLOUDCOST__CLOUDS__AZURE__TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: tenant-id
        - name: CLOUDCOST__CLOUDS__AZURE__SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: subscription-id
        - name: CLOUDCOST__CLOUDS__AZURE__EXPORT__STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: storage-account
        - name: CLOUDCOST__CLOUDS__AZURE__EXPORT__EXPORT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: export-name
        - name: CLOUDCOST__CLOUDS__AZURE__EXPORT__CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: container

        # GCP Configuration
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/credentials/gcp/service-account.json"
        - name: CLOUDCOST__CLOUDS__GCP__CREDENTIALS_PATH
          value: "/etc/credentials/gcp/service-account.json"

        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

        startupProbe:
          httpGet:
            path: /api/health/ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12  # Allow 2 minutes for startup

        volumeMounts:
        - name: gcp-credentials
          mountPath: /etc/credentials/gcp
          readOnly: true
        - name: data-cache
          mountPath: /app/cache
        - name: logs
          mountPath: /app/logs
        - name: app-config
          mountPath: /app/config/production.yaml
          subPath: production.yaml

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
          items:
          - key: service-account.json
            path: service-account.json
      - name: data-cache
        persistentVolumeClaim:
          claimName: data-cache-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: app-config
        configMap:
          name: cost-monitor-config

      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cache-pvc
  labels:
    app: cost-data-service
    component: data-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  labels:
    app: cost-data-service
    component: data-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd