---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cost-monitor-cache-pvc
  labels:
    app: cost-monitor
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
# storageClassName not specified - uses default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cost-monitor-logs-pvc
  labels:
    app: cost-monitor
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# storageClassName not specified - uses default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cost-monitor-config-backup-pvc
  labels:
    app: cost-monitor
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# storageClassName not specified - uses default storage class