---
# Regular Cost Data Collection Job
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cost-data-collection
  labels:
    app: cost-monitor
    component: data-collection
    job-type: regular
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cost-monitor
            component: data-collection
            job-type: regular
        spec:
          restartPolicy: OnFailure
          containers:
          - name: data-collector
            image: cost-monitor/data-service:latest
            command: ["python", "-m", "src.jobs.collect_data"]
            
            env:
            - name: JOB_TYPE
              value: "regular"
            - name: COLLECTION_DAYS
              value: "7"  # Collect last 7 days
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@postgresql:5432/$(POSTGRESQL_DATABASE)"
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: POSTGRESQL_DATABASE
              value: "cost_monitor"
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis-service:6379/0"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
                  
            # Cloud provider credentials
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: tenant-id
            
            resources:
              requests:
                memory: "2Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "1000m"
                
            volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/credentials/gcp
              readOnly: true
              
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
              items:
              - key: service-account.json
                path: service-account.json

---
# Historical Data Collection Job (One-time or manual trigger)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: historical-data-collection
  labels:
    app: cost-monitor
    component: data-collection
    job-type: historical
spec:
  schedule: "0 2 1 * *"  # Monthly on 1st day at 2 AM (or disable with suspend: true)
  suspend: true  # Manually triggered only
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cost-monitor
            component: data-collection
            job-type: historical
        spec:
          restartPolicy: OnFailure
          containers:
          - name: historical-collector
            image: cost-monitor/data-service:latest
            command: ["python", "-m", "src.jobs.collect_historical_data"]
            
            env:
            - name: JOB_TYPE
              value: "historical"
            - name: HISTORICAL_DAYS
              value: "90"  # Collect last 90 days
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@postgresql:5432/$(POSTGRESQL_DATABASE)"
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: POSTGRESQL_DATABASE
              value: "cost_monitor"
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis-service:6379/0"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
                  
            # Cloud provider credentials (same as regular job)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: tenant-id
                  
            resources:
              requests:
                memory: "4Gi"
                cpu: "1000m"
              limits:
                memory: "8Gi"
                cpu: "2000m"
                
            volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/credentials/gcp
              readOnly: true
              
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
              items:
              - key: service-account.json
                path: service-account.json
